# we only need to point to python for the tests to run
language: python
python:
  - "2.7"

# packages to install
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran

# command to install dependencies
install:
  - pip install -U pip pip-tools
  #- pip-compile
  - pip install -r unittests/requirements
  - pip install flake8

# command to run before the tests
before_script:
  - "flake8 unittests --ignore=F401"

# command to run tests
script: 
  - nosetests #unittests/validatetonic.py

