# we only need to point to python for the tests to run
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r unittests/requirements
  - pip install flake8

# command to run before the tests
before_script:
  - "flake8 unittests"  # for the dummy "try"s in mu2 validation

# command to run tests
script: 
  - nosetests #unittests/validatetonic.py

